### ISSUE TITLE
Renovate breaks builds with each npm bump

### ISSUE THREAD

**Issue by enricopolanski** [nuxt-community/style-resources-module#178]
In our organization we are using the `style-resource-module` in multiple projects with satisfaction.

That being said a non indifferent amount of working time, and sometimes multiple working days requiring cross-department interactions go into bumping npm version on the pipelines manually every time `style-resources-module` is updated, and it is hard for us to keep up with this project. This means changing configuration files and going through devops and sysadmins, and I am not including the fact that all devs are also forced into installing new npm versions. This costs us time and money, which would be fine if there were tangible benefits from this behavior, but there are honestly not that I can think of, especially looking at the fact that at the same time the enforced node version is no longer supported or maintained from a long time (node 10).

This package is the only one creating this problem at each release and npm bump and we obviously have thousands of dependencies in each project.

As I am not expert with the Renovate bot and how it works, but I suggest relaxing the npm version requirements if notremoving it completely.

For reference I'm talking about this and the previous line:
https://github.com/nuxt-community/style-resources-module/blob/master/package.json#L55

**Comment by rchl** [comment]
You haven't really explained what the problem is exactly.

The line in https://github.com/nuxt-community/style-resources-module/blob/31af104adb4735126b87edb7f7b2be512bcb0f76/package.json#L54 defines the *minimum* requirements so it shouldn't cause no problems whatsoever if you are using a newer node or npm version. That said, the requirement should be changed to v12, but again, shouldn't be an issue as is.

What problem exactly is this package causing? Maybe screenshot a renovate PR that you are getting updating this package?

**Comment by enricopolanski** [comment]
@rchl I'm referring to npm, nod node, look this line:

```
"npm": ">=6.14.14"
```

getting bumped every release.

This requires us to update all npm versions on all machines and pipelines. I don't think it should be that strict.

**Comment by rchl** [comment]
I've removed the engines key.
