### ISSUE TITLE
Can't make it work in another module

### ISSUE THREAD

**Issue by mmintel** [nuxt-community/style-resources-module#71]
Hi there,

I am trying to use `@nuxtjs/style-resources` from a module but I can't get it to work.

I have a config like:
```
styleResources: {
      scss: [
        '~/theme/styles/abstracts/*.scss'
      ]
    },
```

Passing it to the module directly doesn't work:
```
this.requireModule(['@nuxtjs/style-resources', {
    scss: [
      '~/theme/styles/abstracts/*.scss'
    ]
  } ])
```

Using `path.resolve(__dirname, './styles/abstracts/*.scss')` doesn't work either.
Settings these options as `this.options.styleResources = { ... }` doesn't work.

However the exact same config as mentioned above works when I put it into my `nuxt.config.js` directly.

Any ideas?

**Comment by manniL** [comment]
Might be related to the order of execution (of the modules) :thinking:

**Comment by timelytree** [comment]
Hey @mmintel and @manniL and anyone else arriving here,

I just wanted to confirm that @manniL was right in saying that this issue is related to the order of execution of modules as I recently ran into this issue when developing my own module that required importing of `scss` variables outside of the regular asset flow.

In `nuxt.config.js`:
```js
modules: [
  '~/modules/custom_module',
  '@nuxtjs/style-resources' // <-- make sure to put this AFTER your custom module
]
```

This way, your custom module can make modifications to the `this.options.styleResources.scss` array **_before_** `@nuxtjs/style-resources` runs through that same array.

🎉

**Comment by manniL** [comment]
Thanks for the explanation ☺️ 
Appreciate it! 

Closing here then
