### ISSUE TITLE
Load styleResourcess before other CSS files 

### ISSUE THREAD

**Issue by obaidsamadian** [nuxt-community/style-resources-module#80]
I have both  StyleResources and normal Nuxt CSS. How can I force StyleResources to run before normal Nuxt CSS feature?

Because I don want to my CSS files be overwritten by StyleResources.

**Comment by manniL** [comment]
> Important notice: Do not import actual styles. Use this module only to import variables, mixins, functions (et cetera) as they won't exist in the actual build. Importing actual styles will include them in every component and will also make your build/HMR magnitudes slower. Do not do this!

**Comment by MrToxy** [comment]
@manniL that doesn't address the OP's issue/question and in my case and answer would be really helpful.
If you import the variables/mixins/functions on styled resources but then used on another module that's imported as global css then it breaks because the global css is imported before the styled resources

**Comment by manniL** [comment]
@MrToxy Now I understand the issue!

StyleResources is detached from Nuxt's global CSS. for now, you'd have to add variables there manually as well.
